jobs:
  include:
    - os: linux
      dist: bionic
      arch: amd64
    - os: linux
      dist: focal
      arch: amd64
    - os: linux
      dist: bionic
      arch: arm64
    - os: linux
      dist: focal
      arch: arm64
    - os: osx
      osx_image: xcode11.4
    - os: osx
      osx_image: xcode11.5
    - os: osx
      osx_image: xcode11.6
    - os: osx
      osx_image: xcode12
env:
  global:
  - FRAMEWORK_NAME=MistKit
  - SWIFT_VER=5.2.4
before_install:
  - bash -e ./Scripts/before_install.sh
script:
  - bash -e ./Scripts/script.sh
