#if !canImport(ObjectiveC)
  import XCTest

  extension ArrayTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayTests = [
      ("testUUID", testUUID)
    ]
  }

  extension CharacterMapEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CharacterMapEncoderTests = [
      ("testDefaultInit", testDefaultInit),
      ("testEncode", testEncode)
    ]
  }

  extension FetchRecordQueryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FetchRecordQueryTests = [
      ("testInit", testInit)
    ]
  }

  extension MKAnyRecordTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MKAnyRecordTests = [
      ("testInit", testInit),
      ("testMissingFields", testMissingFields),
      ("testNilIfExists", testNilIfExists),
      ("testValues", testValues),
      ("testValuesIfExists", testValuesIfExists)
    ]
  }

  extension MKDatabaseConnectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MKDatabaseConnectionTests = [
      ("testDefaultInit", testDefaultInit),
      ("testURL", testURL)
    ]
  }

  extension MKEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MKEncoderTests = [
      ("testOptionalData", testOptionalData)
    ]
  }

  extension MKServerResponseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MKServerResponseTests = [
      ("testInitAttemptRecoveryFromFailure", testInitAttemptRecoveryFromFailure),
      ("testInitAttemptRecoveryFromURL", testInitAttemptRecoveryFromURL),
      ("testInitFromResultFailure", testInitFromResultFailure),
      ("testInitFromResultSuccess", testInitFromResultSuccess),
      ("testInitFromResultURL", testInitFromResultURL)
    ]
  }

  extension MKStaticTokenManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MKStaticTokenManagerTests = [
      ("testNoClientWithTokenString", testNoClientWithTokenString),
      ("testWClientWithTokenString", testWClientWithTokenString)
    ]
  }

  extension MKTokenManagerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MKTokenManagerTests = [
      ("testRequest", testRequest),
      ("testWebAuthenticationToken", testWebAuthenticationToken)
    ]
  }

  extension MKURLBuilderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MKURLBuilderTests = [
      ("testURL", testURL)
    ]
  }

  extension RecordNameParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RecordNameParserTests = [
      ("testUUIDs", testUUIDs)
    ]
  }

  extension RequestConfigurationFactoryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RequestConfigurationFactoryTests = [
      ("testConfiguration", testConfiguration)
    ]
  }

  extension ResultTransformerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResultTransformerTests = [
      ("testData", testData),
      ("testNoData", testNoData)
    ]
  }

  extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
      ("testNilIfEmpty", testNilIfEmpty)
    ]
  }

  extension UUIDTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UUIDTests = [
      ("testArray", testArray)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(ArrayTests.__allTests__ArrayTests),
      testCase(CharacterMapEncoderTests.__allTests__CharacterMapEncoderTests),
      testCase(FetchRecordQueryTests.__allTests__FetchRecordQueryTests),
      testCase(MKAnyRecordTests.__allTests__MKAnyRecordTests),
      testCase(MKDatabaseConnectionTests.__allTests__MKDatabaseConnectionTests),
      testCase(MKEncoderTests.__allTests__MKEncoderTests),
      testCase(MKServerResponseTests.__allTests__MKServerResponseTests),
      testCase(MKStaticTokenManagerTests.__allTests__MKStaticTokenManagerTests),
      testCase(MKTokenManagerTests.__allTests__MKTokenManagerTests),
      testCase(MKURLBuilderTests.__allTests__MKURLBuilderTests),
      testCase(RecordNameParserTests.__allTests__RecordNameParserTests),
      testCase(RequestConfigurationFactoryTests.__allTests__RequestConfigurationFactoryTests),
      testCase(ResultTransformerTests.__allTests__ResultTransformerTests),
      testCase(StringTests.__allTests__StringTests),
      testCase(UUIDTests.__allTests__UUIDTests)
    ]
  }
#endif
