#if !canImport(ObjectiveC)
  import XCTest

  extension RecordNameParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RecordNameParserTests = [
      ("testUUIDs", testUUIDs)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(RecordNameParserTests.__allTests__RecordNameParserTests)
    ]
  }
#endif
